# Generated by Django 2.2.10 on 2020-02-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='length',
            field=models.CharField(max_length=15),
        ),
    ]
